#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.10"
# dependencies = ["markdown>=3.5"]
# ///
"""Render the skills README to HTML and verify README-skill sync.

Guard + renderer for the update-skills-readme skill. Verification fails
loudly (exit 2, named problems) so the README cannot silently drift from
the skill set: every skill directory must have a section heading and a
TOC/inventory link, every in-document anchor must resolve, and a scan
that finds zero skills is an error, never a pass.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import markdown
from markdown.extensions.toc import slugify

HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  body {{ font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
         max-width: 920px; margin: 2rem auto; padding: 0 1.25rem;
         color: #1f2328; line-height: 1.55; }}
  h1, h2, h3 {{ line-height: 1.25; }}
  h1 {{ border-bottom: 2px solid #d1d9e0; padding-bottom: .3em; }}
  h2 {{ border-bottom: 1px solid #d1d9e0; padding-bottom: .3em; margin-top: 2em; }}
  h3 {{ margin-top: 1.6em; }}
  a {{ color: #0969da; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  code {{ background: #f6f8fa; border-radius: 4px; padding: .15em .35em;
          font-family: ui-monospace, "Cascadia Mono", Consolas, monospace; font-size: .9em; }}
  pre code {{ display: block; padding: .8em; overflow-x: auto; }}
  table {{ border-collapse: collapse; width: 100%; margin: 1em 0; display: block; overflow-x: auto; }}
  th, td {{ border: 1px solid #d1d9e0; padding: .4em .6em; text-align: left; vertical-align: top; }}
  th {{ background: #f6f8fa; }}
  blockquote {{ border-left: 4px solid #d1d9e0; margin: 1em 0; padding: 0 1em; color: #59636e; }}
  hr {{ border: none; border-top: 1px solid #d1d9e0; margin: 2.5em 0; }}
  em {{ color: #444c56; }}
</style>
</head>
<body>
{body}
<hr>
<p><em>Rendered from README.md by update-skills-readme/scripts/render_html.py — do not edit this file by hand.</em></p>
</body>
</html>
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Verify and render the skills README.")
    parser.add_argument(
        "--readme", type=Path, default=None,
        help="README.md to process (default: the README in this skill's skills root)")
    parser.add_argument(
        "--skills-root", type=Path, default=None,
        help="Directory whose skill subdirectories must be documented (default: the README's directory)")
    return parser.parse_args()


def skill_directories(skills_root: Path) -> list[str]:
    return sorted(
        entry.name for entry in skills_root.iterdir()
        if entry.is_dir() and (entry / "SKILL.md").is_file())


def verify(md_text: str, skill_names: list[str]) -> list[str]:
    problems: list[str] = []
    for name in skill_names:
        if f"### {name}" not in md_text:
            problems.append(f"missing section heading: ### {name}")
        if f"](#{name})" not in md_text:
            problems.append(f"missing TOC/inventory link: #{name}")
    heading_slugs = {
        slugify(match.group(1).strip(), "-")
        for match in re.finditer(r"^#{1,6}\s+(.+)$", md_text, re.M)}
    for anchor in re.findall(r"\]\(#([^)]+)\)", md_text):
        if anchor not in heading_slugs:
            problems.append(f"dead anchor: #{anchor}")
    return problems


def render(md_text: str) -> str:
    body = markdown.markdown(md_text, extensions=["extra", "toc"])
    title_match = re.search(r"^#\s+(.+)$", md_text, re.M)
    title = title_match.group(1).strip() if title_match else "Skills README"
    return HTML_TEMPLATE.format(title=title, body=body)


def main() -> int:
    args = parse_args()
    default_readme = Path(__file__).resolve().parent.parent.parent / "README.md"
    readme = (args.readme or default_readme).resolve()
    if not readme.is_file():
        print(f"ERROR: README not found: {readme}")
        return 2
    skills_root = (args.skills_root or readme.parent).resolve()

    md_text = readme.read_text(encoding="utf-8")
    names = skill_directories(skills_root)
    if not names:
        print(f"ERROR: zero skill directories under {skills_root} — refusing to pass an empty scan")
        return 2

    problems = verify(md_text, names)
    if problems:
        print(f"NOT SYNCED — {len(problems)} problem(s):")
        for problem in problems:
            print(f"  - {problem}")
        return 2

    output = readme.with_suffix(".html")
    output.write_text(render(md_text), encoding="utf-8")
    print(output)
    print(f"verified: {len(names)} skills documented, anchors OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
